[package]
name = "rk3568_driver_block"
version = "0.1.1"
edition = "2024"

[dependencies]
log = { workspace = true }
rdrive = { workspace = true }
sdmmc = { git = "https://github.com/YanQD/sdmmc.git", default-features = false, features = ["pio"] }