[package]
name = "rk3568_driver_clk"
version = "0.1.0"
edition = "2024"

[dependencies]
log = { workspace = true }
somehal = { workspace = true }
rk3568_clk = { git = "https://github.com/arceos-hypervisor/rk3568_clk.git" }